
DROP TABLE ZESPOLY cascade constraints;


CREATE TABLE ZESPOLY
(ID_ZESP NUMERIC(4)  CONSTRAINT PK_ZESP PRIMARY KEY,
NAZWA VARCHAR(20),
ADRES VARCHAR(20) );


INSERT INTO ZESPOLY VALUES (10,'ADMINISTRACJA',      'PIOTROWO 3A');
INSERT INTO ZESPOLY VALUES (20,'SYSTEMY ROZPROSZONE','PIOTROWO 3A');
INSERT INTO ZESPOLY VALUES (30,'SYSTEMY EKSPERCKIE', 'STRZELECKA 14');
INSERT INTO ZESPOLY VALUES (40,'ALGORYTMY',          'WLODKOWICA 16');
INSERT INTO ZESPOLY VALUES (50,'BADANIA OPERACYJNE', 'MIELZYNSKIEGO 30');
 

COMMIT;


